// QA: exercises the claim flow, prize filter (Flip) and poster hover.
import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true })
const p = await b.newPage()
await p.setViewport({ width: 1440, height: 900 })
const errs = []
p.on('pageerror', (e) => errs.push(e.message))
p.on('console', (m) => m.type() === 'error' && errs.push(m.text()))
await p.goto(process.env.URL ?? 'http://localhost:5190/', { waitUntil: 'networkidle0' })
await new Promise((r) => setTimeout(r, 3000))
const wait = (ms) => new Promise((r) => setTimeout(r, ms))
const xpBefore = await p.$eval('.hud .counter__value', (e) => e.textContent)
await p.evaluate(() => document.querySelector('#quests').scrollIntoView())
await wait(1500)
await p.click('.daily__claim .btn')
await wait(2200)
const xpAfter = await p.$eval('.hud .counter__value', (e) => e.textContent)
const toast = await p.$$eval('.toast', (t) => t.map((x) => x.textContent))
const claimed = await p.$eval('.day--today', (e) => e.className)
await p.evaluate(() => document.querySelector('#prizes').scrollIntoView())
await wait(1500)
const buttons = await p.$$('.vault__filter')
await buttons[1].click()
await wait(1400)
const visible = await p.$$eval('.prize', (els) => els.filter((e) => getComputedStyle(e).display !== 'none').map((e) => e.dataset.flipId))
await p.evaluate(() => document.querySelector('#games').scrollIntoView())
await wait(1200)
const posters = await p.$$('.poster')
await posters[3].hover()
await wait(1200)
const active = await p.$eval('.poster.is-active .poster__mech', (e) => e.textContent)
console.log(JSON.stringify({ xpBefore, xpAfter, toast, claimed, visibleLegendary: visible, activePoster: active, errs }, null, 1))
await b.close()
